vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        creationPicture:
            uri_prefix: /images
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer