vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        creationPicture_file:
            uri_prefix: /build/images
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
